FROM nginx:1.27-alpine
COPY index.html /usr/share/nginx/html/index.html
COPY admin.html /usr/share/nginx/html/admin.html
COPY app.js /usr/share/nginx/html/app.js
COPY admin.js /usr/share/nginx/html/admin.js
COPY styles.css /usr/share/nginx/html/styles.css
COPY nginx.conf /etc/nginx/conf.d/default.conf
